set_known_position:
  fields:
    entity_id:
      description: The ID of the entity
      example: 'cover.living_room_blinds'
    position:
      description: The position to set
      example: 50
set_known_tilt_position:
  fields:
    entity_id:
      description: The ID of the entity
      example: 'cover.living_room_blinds'
    position:
      description: The tilt position to set
      example: 30