set_known_position:
  description: Set the known position of the blinds
  fields:
    entity_id:
      name: Entity ID
      description: The ID of the entity
      example: 'cover.living_room_blinds'
    position:
      name: Entity ID
      description: The position to set
      example: 50

set_known_tilt_position:
  description: Set the known tilt position of the blinds
  fields:
    entity_id:
      name: Entity ID
      description: The ID of the entity
      example: 'cover.living_room_blinds'
    position:
      name: Entity ID
      description: The tilt position to set
      example: 50
